image: python:3.9

pipelines:
    default:
        - step:
              name: Configure Application Environment Variables
              script:
                  - cd moneykarma
                  - touch .env
                  - echo APP_PORT=$APP_PORT >> .env
                  - echo APP_URL=$APP_URL >> .env
                  - echo SECRET_KEY=$SECRET_KEY >> .env
                  - echo DATABASE_NAME=$DATABASE_NAME >> .env
                  - echo DATABASE_PORT=$DATABASE_PORT >> .env
                  - echo DATABASE_PASSWORD=$DATABASE_PASSWORD >> .env
                  - echo DATABASE_USER=$DATABASE_USER >> .env
                  - echo DATABASE_HOST=$DATABASE_HOST >> .env
                  - echo REDIS_PASSWORD=$REDIS_PASSWORD >> .env
                  - echo REDIS_PORT=$REDIS_PORT >> .env
                  - echo REDIS_HOST=$REDIS_HOST >> .env
                  - echo REDIS_USER=$REDIS_USER >> .env
        - step:
              name: Build & Test
              caches:
                  - pip
              script:
                  - python -m pip install -r requirements.txt
                  - python manage.py makemigrations
                  - python manage.py migrate
                  - python manage.py test
                  - coverage xml
        - step:
              name: Create Application Artifacts
              script:
                  - git archive --format=tar.gz main -o application.tar.gz
              artifacts:
                  - application.tar.gz
        - step:
              name: Deploy to Heroku Dyno
              deployment: staging
              script:
                  - pipe: atlassian/heroku-deploy:1.2.1
                    variables:
                        HEROKU_API_KEY: $HEROKU_API_KEY
                        HEROKU_APP_NAME: $HEROKU_APP_NAME
                        ZIP_FILE: 'application.tar.gz'
                        WAIT: 'true' # Wait for the deployment to finish