name: MoneyKarma Deployment

on:
  push:
    branches: [ main ]
jobs:
  config:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure Environment Variables
        run: |
          cd moneykarma
          echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
          echo APP_URL=https://${{secrets.HEROKU_APP}}.herokuapp.com >> .env
          echo APP_PORT=80 >> .env
          echo DATABASE_NAME=${{secrets.DATABASE_NAME}} >> .env
          echo DATABASE_USER=${{secrets.DATABASE_USER}} >> .env
          echo DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} >> .env
          echo DATABASE_PORT=${{secrets.DATABASE_PORT}} >> .env
          echo DATABASE_HOST=${{secrets.DATABASE_HOST}} >> .env
          echo REDIS_HOST=${{secrets.REDIS_HOST}} >> .env
          echo REDIS_PORT=${{secrets.REDIS_PORT}} >> .env
          echo REDIS_USER=${{secrets.REDIS_USER}} >> .env
          echo REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}} >> .env
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
      - name: Run Code Coverage Report
        run: |
          coverage xml
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-20.04
    needs: build
    steps: 
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
      - name: Deployed successfully
        run: |
          echo Deployed!!
          echo Application live at: https://${{secrets.HEROKU_APP}}.herokuapp.com